# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QWidget, QApplication, QPushButton, QGroupBox, QMenuBar, QStatusBar, QTextEdit
from PyQt5.QtGui import QFont
from PyQt5.QtCore import QRect, QMetaObject, QCoreApplication

from service.RecordClicks import RecordClicks


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        MainWindow.setFont(font)

        textEditFont = QFont()
        textEditFont.setFamily("微软雅黑")
        textEditFont.setPointSize(10)

        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QRect(0, 30, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.scanDevice_click)

        self.textEdit = QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("logTextEdit")
        self.textEdit.setFont(textEditFont)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QRect(75, 0, 200, 200))

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ADB脚本重放"))
        self.pushButton.setText(_translate("MainWindow", "扫描设备"))

    def scanDevice_click(self):
        #rc = RecordClicks("127.0.0.1", 5037)
        thread = RecordClicks("127.0.0.1", 5037)
        thread.start()
        self.pushButton.setEnabled(False)
